CREATE TABLE SHOP (
sId INT NOT NULL,
Sname VARCHAR(25) NOT NULL,
Street VARCHAR(25) NOT NULL,
City VARCHAR(25) NOT NULL,
StateAb VARCHAR(25) NOT NULL,
ZipCode INT NOT NULL,
Sdate DATE NOT NULL,
Telno INT NOT NULL,
URL VARCHAR(25) ,
PRIMARY KEY(sId)
);

CREATE TABLE DEALER (
dId INT NOT NULL,
Dname VARCHAR(25) NOT NULL,
Street VARCHAR(25) NOT NULL,
City VARCHAR(25) NOT NULL,
StateAb VARCHAR(25) NOT NULL,
ZipCode INT NOT NULL,
PRIMARY KEY(dId)
);

CREATE TABLE DEALER_SHOP (
dId INT NOT NULL,
sId INT NOT NULL,
FOREIGN KEY(dId) REFERENCES DEALER(dId),
FOREIGN KEY(sId) REFERENCES SHOP(sId)
);

CREATE TABLE CONTRACT (
dId INT NOT NULL,
ctId INT,
Sdate DATE,
Ctime TIME,
Cname VARCHAR(25),
PRIMARY KEY(ctID),
FOREIGN KEY(dId) REFERENCES DEALER(dId)
);

CREATE TABLE ITEM (
iId INT NOT NULL,
Iname VARCHAR(25),
Sprice INT,
PRIMARY KEY(iId)
);

CREATE TABLE DEALER_ITEM (
dId INT,
iId INT,
dPrice INT,
FOREIGN KEY(dId) REFERENCES DEALER(dId),
FOREIGN KEY(iId) REFERENCES ITEM(iId)
);


CREATE TABLE OLDPRICE (
iId INT,
Sprice INT,
Sdate DATE,
Edate DATE,
FOREIGN KEY(iId) REFERENCES ITEM(iId)
);

CREATE TABLE ORDERS (
oId INT NOT NULL,
sId INT NOT NULL,
Odate DATE,
Ddate Date,
Amount INT,
cId INT,
PRIMARY KEY(oId),
FOREIGN KEY(sId) REFERENCES SHOP(sId),
FOREIGN KEY(cId) REFERENCES CUSTOMER(cId)
);

CREATE TABLE ORDER_ITEM (
oId INT,
sId INT,
iId INT,
Icount INT,
FOREIGN KEY(sId) REFERENCES SHOP(sId),
FOREIGN KEY(iId) REFERENCES ITEM(iId),
FOREIGN KEY(oId) REFERENCES ORDERS(oId)
);

CREATE TABLE SHOP_ITEM (
sId INT, 
iId INT,
Scount INT,
FOREIGN KEY(sId) REFERENCES SHOP(sId),
FOREIGN KEY(iId) REFERENCES ITEM(iId)
);

CREATE TABLE CUSTOMER (
cId INT,
Cname VARCHAR(25),
Street VARCHAR(25),
City VARCHAR(25),
StateAb VARCHAR(3),
ZipCode INT,
PRIMARY KEY(cId)
);

CREATE TABLE SHOP_CUSTOMER (
sID INT,
cId INT,
FOREIGN KEY(sId) REFERENCES SHOP(sId),
FOREIGN KEY(cId) REFERENCES CUSTOMER(cId)
);

CREATE TABLE EMPLOYEE (
sId INT,
SSN VARCHAR(25),
Ename VARCHAR(25),
Street VARCHAR(25),
City VARCHAR(25),
StateAb VARCHAR(3),
ZipCode INT,
Bdate DATE,
Sdate DATE,
Edate Date,
Etype VARCHAR(25),
Level VARCHAR(25),
Asalary INT,
Agency VARCHAR(25),
Hsalary INT,
Institute VARCHAR(25),
Itype CHAR,
PRIMARY KEY (SSN),
FOREIGN KEY(sId) REFERENCES SHOP(sId)
);
